const images = {
  background: require('../assets/images/background.jpg'),
  creditcard: require('../assets/images/creditcard.jpeg'),
  mastercard: require('../assets/images/mastercard.png'),
  swift: require('../assets/images/Swift.jpeg'),
  user: require('../assets/images/user.png'),
  logo_text: require('../assets/images/logo_text.png'),
  logo_img: require('../assets/images/logo_img.png'),
  kodmark_logo1: require('../assets/images/kodmark_logo1.png'),
  s1: require('../assets/kodmark/slides/1s.jpg'),
  s2: require('../assets/kodmark/slides/2s.jpg'),
  s3: require('../assets/kodmark/slides/3s.jpg'),
  s4: require('../assets/kodmark/slides/4s.jpg'),
  s5: require('../assets/kodmark/slides/5s.jpg'),
  s6: require('../assets/kodmark/slides/6s.jpg'),
  s7: require('../assets/kodmark/slides/7s.jpg'),
  vision: require('../assets/kodmark/visionn.png'),
  mission: require('../assets/kodmark/mission.png'),
  values: require('../assets/kodmark/values.png'),
  argox: require('../assets/kodmark/Masaustu/argox.jpg'),
  ev4t: require('../assets/kodmark/Masaustu/ev4t.png'),
  fvt: require('../assets/kodmark/Masaustu/fvt.jpg'),
  zebragc: require('../assets/kodmark/Masaustu/zebragc.png'),
  qln: require('../assets/kodmark/Anasayfa/qln.jpg'),
  ep4: require('../assets/kodmark/mobil/ep4.jpg'),
  imz: require('../assets/kodmark/mobil/imz.jpg'),
  argoxmbl: require('../assets/kodmark/mobil/argoxmobil.jpg'),
  apf: require('../assets/kodmark/barkodaksesuar/apf.jpg'),
  apn: require('../assets/kodmark/barkodaksesuar/apn.jpg'),
  godex: require('../assets/kodmark/barkodaksesuar/godex.png'),
  towa: require('../assets/kodmark/barkodaksesuar/towa.jpg'),


};
export default images;
